2018-09-26 09:45:43,210 : INFO : bot.py : Slackbot initialized!
2018-09-26 09:46:38,127 : WARNING : bot.py :  SIGINT recieved from the os: program interrupted
2018-09-26 09:46:45,960 : WARNING : bot.py :  SIGINT recieved from the os: program interrupted
2018-09-26 09:46:46,083 : WARNING : bot.py :  SIGINT recieved from the os: program interrupted
2018-09-26 09:46:46,231 : WARNING : bot.py :  SIGINT recieved from the os: program interrupted
2018-09-26 09:46:47,515 : WARNING : bot.py :  SIGINT recieved from the os: program interrupted
2018-09-26 09:46:47,627 : WARNING : bot.py :  SIGINT recieved from the os: program interrupted
2018-09-26 09:46:47,763 : WARNING : bot.py :  SIGINT recieved from the os: program interrupted
2018-09-26 09:46:47,903 : WARNING : bot.py :  SIGINT recieved from the os: program interrupted
2018-09-26 09:46:48,051 : WARNING : bot.py :  SIGINT recieved from the os: program interrupted
2018-09-26 09:46:48,187 : WARNING : bot.py :  SIGINT recieved from the os: program interrupted
2018-09-26 09:46:48,327 : WARNING : bot.py :  SIGINT recieved from the os: program interrupted
2018-09-26 09:46:48,475 : WARNING : bot.py :  SIGINT recieved from the os: program interrupted
2018-09-26 09:46:48,619 : WARNING : bot.py :  SIGINT recieved from the os: program interrupted
2018-09-26 09:46:48,747 : WARNING : bot.py :  SIGINT recieved from the os: program interrupted
2018-09-26 09:47:25,483 : INFO : bot.py : Slackbot initialized!
2018-09-26 09:47:42,741 : INFO : bot.py : User initiated command: nasa
2018-09-26 09:48:54,214 : INFO : bot.py : User initiated command: -help
2018-09-26 09:49:05,876 : INFO : bot.py : Connection terminated by user's exit command.
2018-09-26 09:49:05,876 : INFO : bot.py : User initiated command: secret logout
2018-09-26 09:49:07,050 : ERROR : bot.py : Something happened and Bob-bot stopped.
2018-09-26 09:49:31,479 : INFO : bot.py : Slackbot initialized!
2018-09-26 09:49:47,182 : INFO : bot.py : User initiated command: sup?
2018-09-26 09:49:59,914 : INFO : bot.py : User initiated command: sup?
2018-09-26 09:50:13,533 : ERROR : bot.py : ('Connection aborted.', error(60, 'Operation timed out'))
2018-09-26 09:50:13,533 : INFO : bot.py : Connection error, will retry in 5 seconds
2018-09-26 09:50:18,537 : ERROR : bot.py : Something happened and Bob-bot stopped.
2018-09-26 09:50:18,880 : WARNING : bot.py :  SIGINT recieved from the os: program interrupted
2018-09-26 09:50:18,880 : ERROR : bot.py : Something happened and Bob-bot stopped.
2018-09-26 10:49:46,622:bot.py:Something happened and Bob-bot stopped.
2018-09-26 10:49:46,764:bot.py:Something happened and Bob-bot stopped.
2018-09-26 14:15:19,652 : INFO : bot.py : Slackbot initialized!
2018-09-26 14:18:59,436 : ERROR : bot.py : HTTPSConnectionPool(host='slack.com', port=443): Max retries exceeded with url: /api/api.test (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x110a0ebd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
2018-09-26 14:18:59,436 : INFO : bot.py : Connection error, will retry in 5 seconds
2018-09-26 14:19:04,464 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:19:09,476 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:19:14,486 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:19:19,508 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:19:24,524 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:19:29,539 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:19:34,553 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:19:39,563 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:19:44,578 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:19:49,590 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:19:54,604 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:19:59,615 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:20:04,626 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:20:09,641 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:20:14,651 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:20:19,666 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:20:24,680 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:20:29,693 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:20:34,712 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:20:39,728 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:20:44,739 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:20:49,753 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:20:54,767 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:20:59,782 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:21:04,794 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:21:09,805 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:21:14,817 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:21:19,830 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:21:24,844 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:21:29,856 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:21:34,870 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:21:39,879 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:21:44,892 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:21:49,906 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:21:54,918 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:21:59,938 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:22:04,954 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:22:09,966 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:22:14,977 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:22:19,987 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:22:25,001 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:22:30,013 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:22:35,028 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:22:40,040 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:22:45,056 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:22:50,071 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:22:55,083 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:23:00,098 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:23:05,107 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:23:10,117 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:23:15,132 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:23:20,147 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:23:25,157 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:23:30,170 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:23:35,184 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:23:40,199 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:23:45,213 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:23:50,227 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:23:55,237 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:24:00,252 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:24:05,266 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:24:10,284 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:24:15,295 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:24:20,307 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:24:25,317 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:24:30,333 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:24:35,354 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:24:40,370 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:24:45,388 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:24:50,404 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:24:55,419 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:25:00,438 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:25:05,458 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:25:10,477 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:25:15,494 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:25:20,506 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:25:25,516 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:25:30,530 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:25:35,545 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:25:40,558 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:25:45,574 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:25:50,594 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:25:55,614 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:26:00,633 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:26:05,651 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:26:10,671 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:26:15,684 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:26:20,702 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:26:25,723 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:26:30,742 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:26:35,762 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:26:40,781 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:26:45,791 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:26:50,811 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:26:55,826 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:27:00,846 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:27:05,862 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:27:10,875 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:27:15,896 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:27:20,910 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:27:25,924 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:27:30,932 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:27:35,946 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:27:40,957 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:27:45,977 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:27:50,988 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:27:55,997 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:28:01,010 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:28:06,024 : ERROR : bot.py : Could not connect, will retry in 5 seconds...
2018-09-26 14:28:08,275 : WARNING : bot.py :  SIGTERM recieved from the os: program terminated
2018-09-26 14:28:08,276 : ERROR : bot.py : Something happened and Rover stopped.
2018-09-26 14:28:08,529 : WARNING : bot.py :  SIGTERM recieved from the os: program terminated
